name = "moneyman"
main = "src/index.js"
compatibility_date = "2024-12-01"

[assets]
directory = "public"

[durable_objects]
bindings = [
  { name = "GAME_ROOM", class_name = "GameRoom" }
]

[[migrations]]
tag = "v1"
new_classes = ["GameRoom"]

[[d1_databases]]
binding = "DB"
database_name = "moneyman-db"
database_id = "b7b1b390-d1a2-4217-8709-78ac52020a2a"
